In [1]:
import sklearn

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.pipeline import Pipeline

## Data Importing

In [46]:
titanic_data = pd.read_csv(r"C:\Users\USER\Desktop\webfala\pandas\data\titanic.csv")
titanic_data.head()

,Survived,Pclass,Name,Sex,Age,SibSp,PaCh,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

## Data Preprocessing

In [47]:
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  887 non-null    int64
 1   Pclass    887 non-null    int64
 2   Name      887 non-null    object
 3   Sex       887 non-null    object
 4   Age       887 non-null    float64
 5   SibSp     887 non-null    int64
 6   PaCh      887 non-null    int64
 7   Fare      887 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.6+ KB

In [5]:
titanic_data.describe()

         Survived      Pclass         Age       SibSp        PaCh       Fare
count  887.000000  887.000000  887.000000  887.000000  887.000000  887.00000
mean     0.385569    2.305524   29.471443    0.525366    0.383315   32.30542
std      0.487004    0.836662   14.121908    1.104669    0.807466   49.78204
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.00000
25%      0.000000    2.000000   20.250000    0.000000    0.000000    7.92500
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.45420
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.13750
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.32920

In [6]:
titanic_data.isnull().sum()

Survived    0
Pclass      0
Name        0
Sex         0
Age         0
SibSp       0
PaCh        0
Fare        0
dtype: int64

In [7]:
titanic_data['Survived'].value_counts()

Survived
0    545
1    342
Name: count, dtype: int64

In [5]:
features = ['Pclass','Sex', 'Age', 'SibSp' ,'PaCh','Fare']
target = 'Survived'

In [6]:
x = titanic_data[features].copy()
y = titanic_data[target].copy()

In [14]:
x

     Pclass     Sex   Age  SibSp  PaCh     Fare
0         3    male  22.0      1     0   7.2500
1         1  female  38.0      1     0  71.2833
2         3  female  26.0      0     0   7.9250
3         1  female  35.0      1     0  53.1000
4         3    male  35.0      0     0   8.0500
..      ...     ...   ...    ...   ...      ...
882       2    male  27.0      0     0  13.0000
883       1  female  19.0      0     0  30.0000
884       3  female   7.0      1     2  23.4500
885       1    male  26.0      0     0  30.0000
886       3    male  32.0      0     0   7.7500

[887 rows x 6 columns]

In [14]:
x['Sex'] = x['Sex'].map({'female': 1, 'male': 0})

In [15]:
x.head()

   Pclass  Sex   Age  SibSp  PaCh     Fare
0       3    0  22.0      1     0   7.2500
1       1    1  38.0      1     0  71.2833
2       3    1  26.0      0     0   7.9250
3       1    1  35.0      1     0  53.1000
4       3    0  35.0      0     0   8.0500

## Data Splitting

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =0.2, random_state=42, stratify=y)

In [17]:
print('Training data:', x_train.shape)
print('Testing data:', x_test.shape)

Training data: (709, 6)
Testing data: (178, 6)

## Feature Scaling

In [18]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

## Logistic Regression Model

In [19]:
logistic_model = LogisticRegression(max_iter=800)

logistic_model.fit(x_train_scaled, y_train)

LogisticRegression(max_iter=800)

In [20]:
logistic_prediction = logistic_model.predict(x_test_scaled)

logistic_accuracy = accuracy_score(
    y_test,
    logistic_prediction,
)

print("Logistic Regression Accuracy:", logistic_accuracy * 100)

Logistic Regression Accuracy: 76.96629213483146

In [22]:
print(classification_report(y_test, logistic_prediction))

              precision    recall  f1-score   support

           0       0.80      0.83      0.81       109
           1       0.71      0.68      0.70        69

    accuracy                           0.77       178
   macro avg       0.76      0.75      0.76       178
weighted avg       0.77      0.77      0.77       178

## Decision Tree Model

## Model Training

In [30]:
tree_titanic = DecisionTreeClassifier(
    random_state=42,
    max_depth=3
)

tree_titanic.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=3, random_state=42)

In [49]:
tree_titanic_prediction = tree_titanic.predict(x_test)

tree_titanic_accuracy = accuracy_score(y_test, tree_titanic_prediction)

print('Decision Tree Accuracy', tree_titanic_accuracy * 100)

Decision Tree Accuracy 80.33707865168539

In [36]:
print(classification_report(y_test, tree_titanic_prediction))

              precision    recall  f1-score   support

           0       0.81      0.89      0.85       109
           1       0.79      0.67      0.72        69

    accuracy                           0.80       178
   macro avg       0.80      0.78      0.79       178
weighted avg       0.80      0.80      0.80       178

## Random Forest Model

## Model Training

In [48]:
forest_titanic = RandomForestClassifier(
    max_depth = 5,
    n_estimators = 120,
    random_state = 42
)

forest_titanic.fit(x_train, y_train)

RandomForestClassifier(max_depth=5, n_estimators=120, random_state=42)

In [52]:
forest_titanic_prediction = forest_titanic.predict(x_test)

forest_titanic_accuracy = accuracy_score(y_test, forest_titanic_prediction)

print('Random Forest Accuracy:', forest_titanic_accuracy * 100)

Random Forest Accuracy: 79.7752808988764

In [53]:
print(classification_report(y_test, forest_titanic_prediction))

              precision    recall  f1-score   support

           0       0.79      0.92      0.85       109
           1       0.82      0.61      0.70        69

    accuracy                           0.80       178
   macro avg       0.81      0.76      0.77       178
weighted avg       0.80      0.80      0.79       178

## Support Vector Machine(SVM)

In [54]:
svm_titanic = SVC(
    C= 1000,
    kernel = 'linear',
    random_state=42
    
)

svm_titanic.fit(x_train, y_train)

SVC(C=1000, kernel='linear', random_state=42)

In [60]:
svm_titanic_prediction = svm_titanic.predict(x_test)

svm_titanic_accuracy = accuracy_score(y_test, svm_titanic_prediction)

print('SVM Accuracy:', svm_titanic_accuracy * 100)

SVM Accuracy: 77.52808988764045

In [61]:
print(classification_report(y_test, svm_titanic_prediction))

              precision    recall  f1-score   support

           0       0.80      0.84      0.82       109
           1       0.73      0.67      0.70        69

    accuracy                           0.78       178
   macro avg       0.77      0.76      0.76       178
weighted avg       0.77      0.78      0.77       178

## Using Pipeline

In [81]:
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression())
     
])

pipeline.fit(x_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('model', LogisticRegression())])

In [84]:
y_pred = pipeline.predict(x_test)

pipeline_accuracy = accuracy_score(y_test, y_pred)

print(f"Pipeline Accuracy: {pipeline_accuracy * 100 :.2f}%")

Pipeline Accuracy: 76.97%

In [83]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.83      0.81       109
           1       0.71      0.68      0.70        69

    accuracy                           0.77       178
   macro avg       0.76      0.75      0.76       178
weighted avg       0.77      0.77      0.77       178

In [86]:
results = pd.DataFrame({
      "Model": [
         'Logistic Regression',
         'Decision Tree',
         'Random Forest',
         'SVM',
         'Pipeline'
      ],
      "Accuracy": [
         logistic_accuracy * 100,
         tree_titanic_accuracy * 100,
         forest_titanic_accuracy * 100,
         svm_titanic_accuracy * 100,
         pipeline_accuracy * 100
      ]
})
results.round(2)

                 Model  Accuracy
0  Logistic Regression     76.97
1        Decision Tree     80.34
2        Random Forest     79.78
3                  SVM     77.53
4             Pipeline     76.97

## NOTE: Decision Tree has the highest accuracy so i want to improve its performance by tuning

## Decison Tree Tuning

In [88]:
tree_params = {'max_depth': [5, 8, 12]}

tree_grid = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    tree_params,
    cv=5,
    scoring='accuracy'
)

tree_grid.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=42),
             param_grid={'max_depth': [5, 8, 12]}, scoring='accuracy')

In [89]:
print("Best Parameters:")
print(tree_grid.best_params_)

print("\nBest Cross-Validation Accuracy:")
print(tree_grid.best_score_)

Best Parameters:
{'max_depth': 5}

Best Cross-Validation Accuracy:
0.8082209569473578

In [90]:
best_tree = tree_grid.best_estimator_

tuned_tree_predictions = best_tree.predict(x_test)


tuned_tree_accuracy = accuracy_score(
y_test,
tuned_tree_predictions
)
print("Tuned Decision Tree Accuracy:", tuned_tree_accuracy)

Tuned Decision Tree Accuracy: 0.8033707865168539

In [91]:
print(classification_report(y_test, tuned_tree_predictions))

              precision    recall  f1-score   support

           0       0.80      0.90      0.85       109
           1       0.80      0.65      0.72        69

    accuracy                           0.80       178
   macro avg       0.80      0.78      0.78       178
weighted avg       0.80      0.80      0.80       178

In [92]:
x

     Pclass  Sex   Age  SibSp  PaCh     Fare
0         3    0  22.0      1     0   7.2500
1         1    1  38.0      1     0  71.2833
2         3    1  26.0      0     0   7.9250
3         1    1  35.0      1     0  53.1000
4         3    0  35.0      0     0   8.0500
..      ...  ...   ...    ...   ...      ...
882       2    0  27.0      0     0  13.0000
883       1    1  19.0      0     0  30.0000
884       3    1   7.0      1     2  23.4500
885       1    0  26.0      0     0  30.0000
886       3    0  32.0      0     0   7.7500

[887 rows x 6 columns]

## Creating a Prediction Function and Testing the Model

In [108]:
def predict_survival(name,Pclass, Sex, Age, SibSp, PaCh, Fare):
    sample = pd.DataFrame({
        'Pclass': [Pclass],
        'Sex': [Sex],
        'Age': [Age],
        'SibSp': [SibSp],
        'PaCh': [PaCh],
        'Fare': [Fare]
    })

    prediction = best_tree.predict(sample)[0]
    
    if prediction == 1:
        return f"Congratulations {name}, you survived the trip"
        
    else:
        return f"Unfortunately {name}, you did not survive the trip"

In [105]:
predict_survival('Jemilah', 1, 2, 25.0, 0, 0, 0)

'Congratulations Jemilah, you survived the trip'

In [109]:
predict_survival('Tobi', 2, 0, 40.0, 3, 1, 7.75)

'Unfortunately Tobi, you did not survive the trip'